# Generated by Django 3.2.3 on 2021-05-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_balance',
            field=models.FloatField(default='0.0'),
        ),
    ]
